### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by Zaid-maker** [sujalgoel/slash-suggestion-bot#1]
```js
[ERROR] Request failed
Error: Request failed with status code 403
[ERROR] Request failed
Error: Request failed with status code 403
```

**Comment by sujalgoel** [comment]
You need to invite the bot with `applications.commands` perms from the invite.
**Example:** https://discord.com/api/oauth2/authorize?client_id=BOT_ID&permissions=-1&scope=bot%20applications.commands
